# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "areas", :force => true do |t|
    t.column "areadescricao", :string,   :limit => 60, :default => "", :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "documentos", :force => true do |t|
    t.column "docdescricao",      :string,   :limit => 60,  :default => "", :null => false
    t.column "docautor",          :string,   :limit => 60
    t.column "docpalavras_chave", :string,   :limit => 254, :default => "", :null => false
    t.column "docsinopse",        :text
    t.column "docarquivo",        :string,   :limit => 60,  :default => "", :null => false
    t.column "area_id",           :integer,                                 :null => false
    t.column "tipo_id",           :integer,                                 :null => false
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "tipos", :force => true do |t|
    t.column "tipodescricao", :string,   :limit => 60, :default => "", :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

end
